Fix csvsqlite choking on STDIN, with test.
Curently running `echo -e "a,b,c\n1,2,3" | csvsql` gives this error:

    TypeError: object of type 'cStringIO.StringI' has no len()

This patch fixes it, as well as adds a test case that mocks STDIN.
The error was introduced by pull request #193